# wrangler.toml — configuración mínima para Cloudflare Pages
name = "baicode-landing"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

main = ".worker-next/index.mjs"
assets = { directory = ".worker-next/assets", binding = "ASSETS" }