# wrangler.toml — configuración para Cloudflare Pages + OpenNext
name = "baicode-landing"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

# Directorio principal de salida de OpenNext
pages_build_output_dir = ".open-next"

# El worker generado por OpenNext
main = ".open-next/worker.js"

# Archivos estáticos generados por OpenNext
[assets]
binding = "NEXT_ASSETS"
directory = ".open-next/assets"

# Observabilidad opcional
[observability]
enabled = true
