#:schema node_modules/wrangler/config-schema.json
name = "baicode-landing"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# ✅ Correcto para Next.js + OpenNext
pages_build_output_dir = ".open-next"

[build]
command = "npm run build"
cwd = ""

[env.production]
vars = { NODE_ENV = "production" }
